name: hicap_ci
channels:
- conda-forge
- nodefaults
dependencies:
- python=3.11
- ipython
- jupyter
- notebook
- ipykernel
- matplotlib
- pyyaml
- geopandas
- numpy
- scipy
- pandas
- gdal
- fiona
- rasterio>=1.0
- rasterstats
- shapely
- rtree
- pyproj>=2.0
- pyshp
- xlrd
- openpyxl
- requests
- codecov
- coverage
- flake8
- pytest
- sphinx
- numpydoc
- nbsphinx  # for rendering notebooks in sphinx-generated docs
- sphinx-copybutton
- sphinx_rtd_theme